DEBUG = True

EXIT_NORTH          = 0
EXIT_EAST           = 1
EXIT_SOUTH          = 2
EXIT_WEST           = 3
EXIT_UP             = 4
EXIT_DOWN           = 5
EXIT_NORTHEAST      = 6
EXIT_SOUTHEAST      = 7
EXIT_SOUTHWEST      = 8
EXIT_NORTHWEST      = 9
DIR_NORTH           = 10
DIR_SOUTH           = 11
DIR_EAST            = 12
DIR_WEST            = 13
DIR_UP              = 14
DIR_DOWN            = 15
DIR_NORTHEAST       = 16
DIR_SOUTHEAST       = 17
DIR_SOUTHWEST       = 18
DIR_NORTHWEST       = 19
DIR_RETURN_ORIGIN   = 20

MAX_SIMULTANEOUS_EPOLL_EVENTS  = 10
BUFFER_LENGTH    	= 512
BUFFER_LENGTH_STR 	= "512"
PRINT_LINE_WIDTH 	= 80
NAMES_MIN        	= 5
NAMES_MIN_STR    	= "5"
NAMES_MAX        	= 45
NAMES_MAX_STR    	= "45"
MAX_ROOM_NAME    	= 80
MAX_ROOM_NAME_STR 	= "80"
HASH_LENGTH 	 	= 70
SALT_LENGTH   	 	= 50

# codes relating to standard commands
INVALCMD                 = -8500
SHOWCMDS                 = -8501
SHOWROOM                 = -8502
INVALDIR                 = -8503
LISTPLAYERS              = -8504
PROMPT                   = -8505
MAPIT                    = -8506
ROOM_ONLY                = -8508
ALL_PLAYERS              = -8509
REQUEST_PW_FOR_NEW       = -8510
REQUEST_PW_FOR_EXISTING  = -8511
ATTEMPT_CREATE_USR       = -8512
REQUEST_PW_CONFIRM       = -8513
MISMATCH_PW_SET          = -8514

# codes relating to player creation and handling
THEIR_NAME               = -8600
THEIR_PASSWORD_EXISTING  = -8601
THEIR_PASSWORD_NEWPRELIM = -8602
THEIR_PASSWORD_NEWFINAL  = -8603
USR_CONFIRM_NAME         = -8604
NO_WAIT_STATE            = -8605
PLAYER_CREATION_FAILED   = -8606
PLAYER_CREATION_SUCCESS  = -8607
PLAYER_ALREADY_ONLINE    = -8608
INCORRECT_PASSWORD       = -8609
UNABLE_TO_RETRIEVE_CHAR  = -8610
NAME_UNAVAILABLE         = -8611
ALPHANUM_NAMES_ONLY      = -8612
NAME_TOO_LONG            = -8613
NAME_TOO_SHORT           = -8614
NAME_NOT_WITHIN_PARAMS   = -8615

# codes for handling coordinates
X_COORD_REQUEST          = -8650
Y_COORD_REQUEST          = -8651
Z_COORD_REQUEST          = -8652

# codes for room-relates commands
WAIT_ENTER_NEW_ROOM_NAME       = -8700
WAIT_CONFIRM_NEW_ROOM_NAME     = -8701
WAIT_ENTER_NEW_ROOM_DESC       = -8702
WAIT_CONFIRM_NEW_ROOM_DESC     = -8703
PRINT_PROVIDE_NEW_ROOM_NAME    = -8704
PRINT_PROVIDE_NEW_ROOM_DESC    = -8705
PRINT_ROOM_EXIT_CHANGED        = -8706
PRINT_ROOM_FLAG_CHANGED        = -8707
PRINT_ROOM_ALREADY_EXISTS      = -8708
ADJUSTING_ROOM_NAME            = -8712
ADJUSTING_ROOM_DESC            = -8713
ADJUSTING_ROOM_EXIT            = -8714
ADJUSTING_ROOM_FLAG            = -8715
PRINT_CONFIRM_NEW_ROOM_NAME    = -8716
PRINT_CONFIRM_NEW_ROOM_DESC    = -8717
PRINT_ADJUSTMENT_SUCCESSFUL    = -8718
PRINT_COULDNT_ADJUST_ROOM      = -8719
PRINT_EXITING_CMD_WAIT         = -8720
PRINT_ENTER_NEW_ROOM_DIR       = -8721
PRINT_ENTER_DIR_TO_REMOVE      = -8722
PRINT_INSUFFICIENT_PERMISSIONS = -8723
PRINT_REMOVED_FROM_ROOM        = -8724
PRINT_TOGGLED_ROOM_EXIT        = -8725
PRINT_COULDNT_TOGGLE_EXIT      = -8726
PRINT_COULDNT_EXIT_NO_ROOM     = -8727

PRINT_ROOM_REMOVAL_CHECK       = -8730
PRINT_ROOM_REMOVAL_CONFIRM     = -8731
PRINT_ROOM_REMOVAL_SUCCESS     = -8732
PRINT_ROOM_REMOVAL_FAILURE     = -8733
PRINT_ROOM_CREATION_GIVE_DIR   = -8734
PRINT_PROVIDE_ROOM_EXIT_NAME   = -8735
PRINT_PROVIDE_ROOM_FLAG_NAME   = -8736
PRINT_ROOM_CREATION_CONFIRMALL = -8737
PRINT_ROOM_CREATION_CANNOT     = -8738
PRINT_ROOM_CREATION_SUCCESS    = -8739
PRINT_ROOM_CREATION_FAILURE    = -8740

WAIT_ROOM_REMOVAL_CHECK        = -8741
WAIT_ROOM_REMOVAL_CONFIRM      = -8742
WAIT_ROOM_CREATION_DIR         = -8743
WAIT_ROOM_CREATION_NAME        = -8744
WAIT_ROOM_CREATION_DESC        = -8745
WAIT_ROOM_CREATION_CONF        = -8746
WAIT_ENTER_FLAG_NAME           = -8747
WAIT_ENTER_EXIT_NAME		   = -8748
